language: python
before_install:
        - "sudo add-apt-repository ppa:xav0989/libgit2 -y"
        - "sudo apt-get update -y"
        - "sudo apt-get install -y libevent-dev libgit2-dev python-dev"
python:
        - "2.7"
script: "nosetests tests/"
