language: "python"
services:
        - "mongodb"
before_install:
        - "sudo apt-get install -y libev-dev python-dev"
python:
        - "2.7"
before_script:
        - "psql -c 'create database mirrit;' -U postgres"
script: "nosetests tests/"
